name: Update Homebrew Formula

description: |
  Automatically update cf-purge.rb with the latest release URL and SHA256 from the GoLang app repo.

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6am UTC
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repo
        uses: actions/checkout@v4

      - name: Get latest release info
        id: get_release
        run: |
          curl -s https://api.github.com/repos/Dzhuneyt/cf-purge/releases/latest > release.json
          TAG=$(jq -r .tag_name release.json)
          TARBALL_URL=$(jq -r '.tarball_url' release.json)
          
          if [ -z "$TARBALL_URL" ] || [ "$TARBALL_URL" = "null" ]; then
            echo "Could not find tarball_url in the release" >&2
            exit 1
          fi
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "url=$TARBALL_URL" >> $GITHUB_OUTPUT

      - name: Download release asset
        run: |
          curl -L "${{ steps.get_release.outputs.url }}" -o asset.tar.gz

      - name: Calculate SHA256
        id: sha
        run: |
          SHA256=$(shasum -a 256 asset.tar.gz | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Update cf-purge.rb
        run: |
          sed -i.bak "s|url \".*\"|url \"${{ steps.get_release.outputs.url }}\"|" cf-purge.rb
          sed -i.bak "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha256 }}\"|" cf-purge.rb
          rm cf-purge.rb.bak
          cat cf-purge.rb

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cf-purge.rb
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update formula to ${{ steps.get_release.outputs.tag }}"
          git push
